### ISSUE TITLE
Full naming support for route tables rather than just the prefix

### ISSUE THREAD

**Issue by pratik-parikh01** [oracle-terraform-modules/terraform-oci-vcn#103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While using this module, route tables are created called, `nat-route` and `internet-route`. There is a support for adding a prefix using `var.label_prefix` but what I would like is to make this entire name configurable rather than just the prefix

### New or Affected Resource(s)

Route table display names

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used.
```

**Comment by hyder** [comment]
Resolved in https://github.com/oracle-terraform-modules/terraform-oci-vcn/pull/137
