### ISSUE TITLE
Add support for reserved IP on NAT Gateway

### ISSUE THREAD

**Issue by rbair23** [oracle-terraform-modules/terraform-oci-vcn#14]
In production it is often useful to have a stable IP address for the NAT in a VCN across rebuilds of the VCN. Sometimes a customer will have opened their firewall for a specific IP, so it is important to maintain that same IP over time even as the underlying infrastructure is rebuilt.

```hcl
resource "oci_core_public_ip" "nat_public_ip" {
  compartment_id = var.compartment_id
  lifetime       = "RESERVED"
  display_name   = "IP Address for NAT"
}
```

For this project, it would be enough to just have a property that I can feed the reserved IP address into. My base terraform script will create the reserved IP and then invoke this one, passing the IP.

**Comment by hyder** [comment]
That's a reasonable request. We'll work on this.

**Comment by kral2** [comment]
This is the current standard VCN block:

```HCL
module "vcn" {
  source = "../"

  # general oci parameters
  compartment_id = var.compartment_id
  label_prefix   = var.label_prefix
  tags           = var.tags

  # vcn parameters
  create_drg               = var.create_drg
  internet_gateway_enabled = var.internet_gateway_enabled
  lockdown_default_seclist = var.lockdown_default_seclist
  nat_gateway_enabled      = var.nat_gateway_enabled
  service_gateway_enabled  = var.service_gateway_enabled
  vcn_cidr                 = var.vcn_cidr
  vcn_dns_label            = var.vcn_dns_label
  vcn_name                 = var.vcn_name

  # gateways parameters
  drg_display_name = var.drg_display_name
}
```

I am thinking about adding a new Input Variable under `#gateway parameters` section that would be optional.
`nat_gateway_public_ip = <string>`.

```HCL
...
  vcn_dns_label            = var.vcn_dns_label
  vcn_name                 = var.vcn_name

  # gateways parameters
  drg_display_name        = var.drg_display_name
  nat_gateway_public_ip   = <a valid string>
}
```

3 possible cases:

1. By default, if `nat_gateway_public_ip` is not initialized by the module user, the module will act as of today : a NAT Gateway with an ephemeral public IP.

2. If a valid [`oci_core_public_ip`](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_public_ip) is passed by the module user, module will use it to set `oci_core_nat_gateway.nat_gateway.public_ip_id`

3. if keyword `RESERVED` is passed by the module user, then VCN module will create a reserved public IP and use it for `oci_core_nat_gateway.nat_gateway.public_ip_id`

Case 2 gives full control over the lifecyle : NAT public IP would survive a vcn destroy/recreate but requires the user to handle the public ip creation.

Case 3 do not permit to keep the same NAT public IP if vcn is destroyed/recreated but, will survive NAT Gateway  destroy/recreate and assist the user in provisioning a reserved public IP.
