### ISSUE TITLE
Add a DRG and associate it with the VCN

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-vcn#16]
When adding connectivity to on-premise networks, we need to to use a DRG.

**Comment by kral2** [comment]
I have working code for this issue that I will be able to backport here.

**Comment by kral2** [comment]
:tada: This issue has been resolved in version v2.2.0 :tada:

The release is available [here](https://github.com/oracle-terraform-modules/terraform-oci-vcn/releases/tag/v2.2.0)
