### ISSUE TITLE
Add custom route rules  to the NAT gateway

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-vcn#17]
When adding connectivity to on premise networks, we need to be able to add configurable route rules to the relevant on-premise CIDR blocks and route it through a DRG. These route rules should be added to the NAT route table as it will be used by private subnets.

**Comment by hyder** [comment]
Dependant on #16

**Comment by kral2** [comment]
:tada: This issue has been resolved in version v2.2.0 :tada:

The release is available [here](https://github.com/oracle-terraform-modules/terraform-oci-vcn/releases/tag/v2.2.0)
