### ISSUE TITLE
obsolete variables for provider configuration

### ISSUE THREAD

**Issue by fbreckle** [oracle-terraform-modules/terraform-oci-vcn#2]
Hi,

there are no references in this module to the variables `api_fingerprint`, 
'api_private_key_path`, `region`, `tenancy_id, user_id`. They all seem to be provider related.
Since [providers should be passed from outside the module](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules) anyway, they can be removed.
In particulary, the `region` does not default to anything, so I have to pass it even if it does nothing.

**Comment by hyder** [comment]
thanks. we'll remove them.

**Comment by hyder** [comment]
Resolved in #4
