### ISSUE TITLE
Gateway creation variables misnamed

### ISSUE THREAD

**Issue by kral2** [oracle-terraform-modules/terraform-oci-vcn#24]
From PR #23 review: "If your variable is controlling a behaviour, use imperative style to name it e.g. lockdown_default_seclist"

These variables should be renamed to the suggested name to be in line with this coding convention.
- var.internet_gateway_enabled -> var.create_internet_gateway
- var.nat_gateway_enabled -> var.create_nat_gateway
- var.service_gateway_enabled -> var.create_service_gateway

It is imperative mode, but I also suggest to change the verb from `enable` to `create`.
`enable` and `create` are different verbs from the API point of view, and we should reflect it more precisely, as the current module action is "create in enabled state".

For example, it is totally possible to *create* a nat gateway with a *disabled* state.

Yet, renaming these variables is a breaking change and would need a major version bump.
Plan should be to change these variables on the next major version but start using the suggested naming here for any new variable that controls a behaviour.

**Comment by hyder** [comment]
Good point. This impacts on other modules such as bastion, operator and oke as well. Let's keep this open and do it in next major release as you said and we do the same thing in other modules

**Comment by hyder** [comment]
The merge activities on this issue are due to incorrect linking with PR #27
