### ISSUE TITLE
Single format for documentation files

### ISSUE THREAD

**Issue by kral2** [oracle-terraform-modules/terraform-oci-vcn#26]
The repository documentation is currently a combination of Markdown and AsciiDoc.

We are in a situation where some files exists in both format and the same content requires to be updated twice.
Also contributors needs to constantly switch between between two markup languages.

While AsciiDoc allows for a more structured content, Terraform registry only supports Markdown.
I would suggest to use Markdown only.

Even if it is more limited that AsciiDoc, it is more common and would help when:
- integrating with other solutions: if we start to automate some parts of the documents, Markdown support is more easily found than AsciiDoc
- new contributors make changes: potentially less "new things" to learn before contributing

**Comment by hyder** [comment]
While this module's docs is simple enough to get away with Markdown, we've had a lot of formatting issues with Markdown in the past with other modules that require more structured documentation.

As such, we spent a considerable effort rewriting all related module docs (vcn, bastion, operator, oke, olcne) in AsciiDoc.

See https://mister-gold.pro/posts/en/asciidoc-vs-markdown/.

There's no need to 'learn' AsciiDoc like you would for a conventional language if all you're doing is writing docs with it. The reference is extensive and usually sufficient: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/.

So, we'll duplicate in Markdown **only** the README of the main repo for the needs of Terraform registry. This README shouldn't change too often anyway. All other docs will be in AsciiDoc.

**Comment by kral2** [comment]
Agree with your points : Markdown is all but a standard when it comes to rendering ... My point of view is heavily influenced by Terraform registry capabilities, documentation of modules that use only basic formatting and no nested structures.

If dual-format is limited to README, we could probably auto-generate the Markdown version from the AsciiDoc version using tools like Pandoc or similar.
