### ISSUE TITLE
add support of Reserved IP provisionning for NAT Gateway

### ISSUE THREAD

**Issue by kral2** [oracle-terraform-modules/terraform-oci-vcn#53]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Issue #14 added support for using a reserved IP created outside of this module by refering the resource's OCID.
But provisioning of this reserved IP is currently not handled by the module.

This issue propose to resolve this by adding a new feature that would:
- provision a new Reserved IP
- Associate the Reserved IP with the NAT gateway created by the module.

This feature should preserve the possibility for the user to reuse an existing Reserved IP. 

### New or Affected Resource(s)

To be evaluated.

### Potential Terraform Configuration

```hcl
# Nothing yet. 
```

**Comment by syedthameem85** [comment]
@kral2 - This will address only "Case 3 do not permit to keep the same NAT public IP if vcn is destroyed/recreated but, will survive NAT Gateway destroy/recreate and assist the user in provisioning a reserved public IP."  Is the  understanding correct ? cc: @hyder

**Comment by hyder** [comment]
resolved in #115
