### ISSUE TITLE
simplify the custom route rules variables schema

### ISSUE THREAD

**Issue by kral2** [oracle-terraform-modules/terraform-oci-vcn#57]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Custom route rules feature introduced by fixing #17 in [release v2.2.0](https://github.com/oracle-terraform-modules/terraform-oci-vcn/releases/tag/v2.2.0) use twi new module Input Variables:
- `var.internet_gateway_route_rules`
- `var.nat_gateway_route_rules`

They are both [complex structural types](https://www.terraform.io/docs/language/expressions/type-constraints.html#structural-types).

```
type = list(object({
  destination       = string
  destination_type  = string
  network_entity_id = string
  description       = string
}))
```

Advantages:
- the variable is self-documenting
- we enforce a schema that is expected by OCI API.

Drawbacks:
- it can be complex for new users,
- seems Resource Manager do not handle objects well
- all fields becomes required. [Optional object type attributes is still an experimental feature from 0.14](https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes)

The goal is to simplify usage of these new variables, without loosing too much on schema enforcement and documentation.

- solution 1: use type `map(any)`
- solution 2: use type `list(map(any))` or `list(map(string))`
- solution 3: use type `list(object)` with optional attributes

_Solution 3 may be a long term approach, when optional attributes will become a supported feature of Terraform. It gives both self-documented variable and simplified input with optional attributes._

With `map(any)`, the module user would have to provide a key for each rule despite the OCI API do not require it and the accepted schema needs to be discovered by the user from documentation. That's not simplification.

Using `list(map(any))` we we loose some constraint validation in comparison with `list(map(string))`.

I would suggest using `list(map(string))` instead of the current `list(object)` and reevaluate this choice when Optional object type attributes becomes a supported feature.

The change can be transparent for the module users in later releases if we stay with a list type at the primary level.

### Potential Terraform Configuration

```hcl
variable "nat_gateway_route_rules" {
type = list(map(string))
default = [
  {
    destination = "192.168.0.0/16" # Route Rule Destination CIDR
    destination_type = "CIDR_BLOCK"
    network_entity_id = "drg"
    description = "Terraformed - User added Routing Rule"
    },
    {
      destination = "172.16.0.0/16"
      destination_type  = "CIDR_BLOCK"
      network_entity_id = module.vcn.drg_id
      description  = "Terraformed - User added Routing Rule"
    },
  ]
}
```

**Comment by karthicgit** [comment]
@kral2 the example given in default is a map(any) please change the { to [ .
