### ISSUE TITLE
add LPG Gateway introspection to add LPG specific routes in route_rules

### ISSUE THREAD

**Issue by snafuz** [oracle-terraform-modules/terraform-oci-vcn#89]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add LPG gateway introspection to add LPG-specific routes to other gateways route_rules by adding a predefined value `lpg`. This is the same approach used for  other gateways with predefined values such as `drg`, `internet_gateway`, etc..

### New or Affected Resource(s)

oci_core_route_table * in [](vcn_gateway.tf)
oci_core_local_peering_gateway

### Potential Terraform Configuration

```hcl
  local_peering_gateways  = {lpg1_name = { route_table_id = "", peer_id = "possible_id_of_peered" }}
  nat_gateway_route_rules = [
    {
      destination       = "172.18.0.0/16",
      destination_type  = "CIDR_BLOCK",
      network_entity_id = "nat_gateway",
      description       = "already works, uses the id of the NAT GW created by the OKE module"
    },
    {
      destination       = "172.19.0.0/16",
      destination_type  = "CIDR_BLOCK",
      network_entity_id = "LPG@lpg1_name",
      description       = "this doesn't work right now, the network_entity_id would be the id of the LPG created above"
    }
  ]
```

### References

Initially raised here: oracle-terraform-modules/terraform-oci-oke#514

**Comment by thpham** [comment]
@snafuz I created a PR that address your proposition, because my team and I, are facing the same challenge. Would you be interested to have a look and test that it is how you thought it ?
